---
when:
  - event: [tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

runs_on: [success, failure]

steps:
  - name: matrix
    image: quay.io/thegeeklab/wp-matrix
    settings:
      homeserver:
        from_secret: matrix_homeserver
      access_token:
        from_secret: matrix_access_token
      roomid:
        from_secret: matrix_roomid
      user_id:
        from_secret: matrix_user_id
    when:
      - status: [success, failure]

depends_on:
  - docs
